### ISSUE TITLE
Update angular 7 to 9

### ISSUE THREAD

**Issue by DevKleber** [cesarrew/ng2-currency-mask#139]
```
TypeError: Cannot read property 'id' of undefined
    at registerNgModuleType (/home/myname/angular/myprogram/frontend/node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:35565:1)
    at /home/myname/angular/myprogram/frontend/node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:35583:1
    at Array.forEach (<anonymous>)
    at registerNgModuleType (/home/myname/angular/myprogram/frontend/node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:35579:1)
    at new NgModuleFactory$1 (/home/myname/angular/myprogram/frontend/node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:35747:1)
    at compileNgModuleFactory__POST_R3__ (/home/myname/angular/myprogram/frontend/node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:41519:1)
    at PlatformRef.bootstrapModule (/home/myname/angular/myprogram/frontend/node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:41884:1)
    at Module../src/main.ts (/home/myname/angular/myprogram/frontend/src/main.ts:11:26)
    at __webpack_require__ (http://localhost:4201/runtime.js:85:30)
    at Object.0 (http://localhost:4201/main.js:2749:18)

```
![EX](https://i.imgur.com/QmEXkca.png)
Format: ![Alt Text](url)

**Comment by FlavioRoberto** [comment]
ERROR in node_modules/ng2-currency-mask/src/currency-mask.module.d.ts:1:22 - error NG6002: Appears in the NgModule.imports of CompartilhadoModule, but could not be resolved to an NgModule class.

This likely means that the library (ng2-currency-mask) which declares CurrencyMaskModule has not been processed correctly by ngcc, or is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.

**Comment by rscherer** [comment]
Same problem as #138 
Using **ngx-currency** solved my problem without any implementation changes.

**Comment by cesarrew** [comment]
Please upgrade to version 9.0.0.
