### ISSUE TITLE
TypeError: Cannot read property 'kind' of undefined

### ISSUE THREAD

**Issue by DavidML3** [cesarrew/ng2-currency-mask#143]
In Angular 8 and Angular 9 with the latest version of ng2-currency-mask when building for production I keep getting this error 

ERROR in ./node_modules/ng2-currency-mask/__ivy_ngcc__/fesm5/ng2-currency-mask.js
Module build failed (from ./node_modules/@angular-devkit/build-optimizer/src/build-optimizer/webpack-loader.js):
TypeError: Cannot read property 'kind' of undefined
    at isAngularDecoratorMetadataExpression (C:\Users\zkpab6j\GitRepository\lookandfeel_angular\correctiontool-app\node_modules\@angular-devkit\build-optimizer\src\transforms\scrub-file.js:265:35)
    at checkNodeForDecorators (C:\Users\zkpab6j\GitRepository\lookandfeel_angular\correctiontool-app\node_modules\@angular-devkit\build-optimizer\src\transforms\scrub-file.js:77:21)
    at visitNodes (C:\Users\zkpab6j\GitRepository\lookandfeel_angular\correctiontool-app\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:16631:30)
    at Object.forEachChild (C:\Users\zkpab6j\GitRepository\lookandfeel_angular\correctiontool-app\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:16857:24)
    at checkNodeForDecorators (C:\Users\zkpab6j\GitRepository\lookandfeel_angular\correctiontool-app\node_modules\@angular-devkit\build-optimizer\src\transforms\scrub-file.js:68:31)
    at visitNode (C:\Users\zkpab6j\GitRepository\lookandfeel_angular\correctiontool-app\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:16622:24)
    at Object.forEachChild (C:\Users\zkpab6j\GitRepository\lookandfeel_angular\correctiontool-app\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:16752:21)
    at checkNodeForDecorators (C:\Users\zkpab6j\GitRepository\lookandfeel_angular\correctiontool-app\node_modules\@angular-devkit\build-optimizer\src\transforms\scrub-file.js:68:31)
    at visitNode (C:\Users\zkpab6j\GitRepository\lookandfeel_angular\correctiontool-app\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:16622:24)
    at Object.forEachChild (C:\Users\zkpab6j\GitRepository\lookandfeel_angular\correctiontool-app\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:16809:24)
    at checkNodeForDecorators (C:\Users\zkpab6j\GitRepository\lookandfeel_angular\correctiontool-app\node_modules\@angular-devkit\build-optimizer\src\transforms\scrub-file.js:68:31)
    at visitNode (C:\Users\zkpab6j\GitRepository\lookandfeel_angular\correctiontool-app\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:16622:24)
    at Object.forEachChild (C:\Users\zkpab6j\GitRepository\lookandfeel_angular\correctiontool-app\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:16820:24)
    at checkNodeForDecorators (C:\Users\zkpab6j\GitRepository\lookandfeel_angular\correctiontool-app\node_modules\@angular-devkit\build-optimizer\src\transforms\scrub-file.js:68:31)
    at visitNode (C:\Users\zkpab6j\GitRepository\lookandfeel_angular\correctiontool-app\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:16622:24)
    at Object.forEachChild (C:\Users\zkpab6j\GitRepository\lookandfeel_angular\correctiontool-app\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:16716:21)

**Comment by DavidML3** [comment]
I have searched older issues pertaining to this and none have been solved. What is the workaround for this using Angular 8 or 9?
