### ISSUE TITLE
After i install it gave me error in console InjectionToken is not a constructor 

### ISSUE THREAD

**Issue by somnathswami** [cesarrew/ng2-currency-mask#54]
zone.js:522 Unhandled Promise rejection: core_1.InjectionToken is not a constructor ; Zone: angular ; Task: Promise.then ; Value: TypeError: core_1.InjectionToken is not a constructor
    at Object.1054 (currency-mask.config.js:4)
    at _webpack_require_ (bootstrap d02c331fe602561fc89b:52)
    at Object.1010 (currency-mask.directive.js:5)
    at _webpack_require_ (bootstrap d02c331fe602561fc89b:52)
    at Object.1053 (index.js:6)
    at _webpack_require_ (bootstrap d02c331fe602561fc89b:52)
    at Object.957 (0.chunk.js:5136)
    at _webpack_require_ (bootstrap d02c331fe602561fc89b:52)
    at src async:15
    at ZoneDelegate.webpackJsonp.951.ZoneDelegate.invoke (zone.js:334)
    at Object.onInvoke (ng_zone.js:273)
    at ZoneDelegate.webpackJsonp.951.ZoneDelegate.invoke (zone.js:333)
    at Zone.webpackJsonp.951.Zone.run (zone.js:126)
    at zone.js:713
    at ZoneDelegate.webpackJsonp.951.ZoneDelegate.invokeTask (zone.js:367) TypeError: core_1.InjectionToken is not a constructor
    at Object.1054 (http://localhost:4200/0.chunk.js:4379:32)
    at _webpack_require_ (http://localhost:4200/inline.bundle.js:53:30)
    at Object.1010 (http://localhost:4200/0.chunk.js:2030:30)
    at _webpack_require_ (http://localhost:4200/inline.bundle.js:53:30)
    at Object.1053 (http://localhost:4200/0.chunk.js:4366:10)
    at _webpack_require_ (http://localhost:4200/inline.bundle.js:53:30)
    at Object.957 (http://localhost:4200/0.chunk.js:5136:76)
    at _webpack_require_ (http://localhost:4200/inline.bundle.js:53:30)
    at http://localhost:4200/main.bundle.js:11818:10
    at ZoneDelegate.webpackJsonp.951.ZoneDelegate.invoke (http://localhost:4200/polyfills.bundle.js:2907:26)
    at Object.onInvoke (http://localhost:4200/vendor.bundle.js:35548:37)
    at ZoneDelegate.webpackJsonp.951.ZoneDelegate.invoke (http://localhost:4200/polyfills.bundle.js:2906:32)
    at Zone.webpackJsonp.951.Zone.run (http://localhost:4200/polyfills.bundle.js:2699:43)
    at http://localhost:4200/polyfills.bundle.js:3286:57
    at ZoneDelegate.webpackJsonp.951.ZoneDelegate.invokeTask (http://localhost:4200/polyfills.bundle.js:2940:31)

**Comment by cesarrew** [comment]
What Angular version are you using? You should use the version 2.x.x for Angular 2.x.x applications and the version 4.x.x for Angular 4.x.x applications.

**Comment by tobiasetter** [comment]
@somnathswami  Change the version in your package.json to "less than 4.x.x" like the following example:

`"ng2-currency-mask": "<4.0.0",`
